### ISSUE TITLE
Dependency not available, install fails

### ISSUE THREAD

**Issue by MarcDiethelm** [assemble/assemble-less#10]
This dependency listed in package.json is not available anymore.

https://github.com/cloudhead/less.js/tarball/1.4.1-wip

**Comment by jonschlinkert** [comment]
thanks! had no idea. will fix

**Comment by jonschlinkert** [comment]
Fixed. thanks!

**Comment by MarcDiethelm** [comment]
Awesome! Thank you...

May I interest you in my very humble (yet useful) grunt plugin? https://github.com/MarcDiethelm/grunt-less-imports

**Comment by MarcDiethelm** [comment]
Hi. Same issue again. This time with the newer https://github.com/less/less.js/tarball/1.5.0-wip

**Comment by jonschlinkert** [comment]
Want to do a pull request with the update?

**Comment by MarcDiethelm** [comment]
I'd be happy to help. I've not figured out how the tarball is used though. Or how the less versions in the tarball are chosen. :)

**Comment by jonschlinkert** [comment]
already done, thx

**Comment by jonschlinkert** [comment]
btw, the only reason I had 1.5.0 as a tarball is that it was inconsistently (or not ever) published to npm. I'm on the core team for less, so I wanted to have that as the default version for this repo so I could test newer features. this is the same reason I added the feature to allow users to define a specific version of less to use for compiling... anyway, sorry for the confusion.

**Comment by MarcDiethelm** [comment]
Ah, thanks for clearing this up. Probably not the best idea to rely on a tarball that may or may not exist in the published version though. Or an unreleased version of less for that matter! That's what `npm link` is for, local testing, no? (I see that in your new commit you are depending on less@1.5.0. So you did publish it after all. :) Are you planning on re-introducing the use of tarballs for later versions? I hope not. I'm using assemble-less in my framework and the dependency on tarballs of unreleased less versions somewhat compromises its robustness.

> I'm on the core team for less

Totally aware of the fact.

**Comment by jonschlinkert** [comment]
> Are you planning on re-introducing the use of tarballs for later versions?

Whatever is the best solution at any given time, based on the goals of this project. 

> Or an unreleased version of less for that matter! 

The focus of this plugin will continue to be innovation. I want to test new ideas here and new Less.js features (including unreleased), and this is supported by the first paragraph on the README: 

> This project is a fork of the popular grunt-contrib-less plugin by the talented Tyler Kellen. Please use that plugin if you require something stable and dependable.

For your use case, it might be better to use grunt-contrib-less for projects that need that stability, and I'd love to have you continue to support this project when you are looking to solve problems that grunt-contrib-less can't solve (and won't because of the experimental nature of the solutions).

**Comment by jonschlinkert** [comment]
btw, I do understand and view, do you have any suggestions on how we can keep this project focused on "the next version of Less.js", while also ensuring stability? I have resisted bundling dependencies into any project I'm on, but in this case maybe it's the best solution... I could just include the most current, stable version of less.js in the project, and make the wip version of less a devDependency? would that be okay to you?

**Comment by MarcDiethelm** [comment]
I would much prefer to use your plugin. The banner option for me is invaluable, because it allows me to inject a dynamic base URI into the generated CSS for use with images, sprites and fonts.

Somehow I seem to have forgotten about the experimental nature of assemble-less. So I'm in no position to tell you what to do.

Having said that, I think your proposal is excellent! A perfect balance of having a reliable library that can easily be used to experiment with some upcoming features of LessCSS. Just what I want.

**Comment by MarcDiethelm** [comment]
Apparently banner is not working this way anymore. I'll create a new issue.

**Comment by jonschlinkert** [comment]
> I think your proposal is excellent!

awesome! I'll do that as soon as I have a chance. 

> banner is not working this way anymore.

Yeah create an issue for that, I'll get it fixed for you.

**Comment by tony0918** [comment]
I got the following error message during the `npm install` for _grunt-refactor_. Please help.

```
$ npm install
npm ERR! fetch failed https://github.com/cloudhead/less.js/tarball/1.5.0-wip
npm ERR! Error: 404 Not Found
npm ERR!     at WriteStream.<anonymous> (c:\Program Files\nodejs\node_modules\npm\lib\utils\fetch.js:58:12)
npm ERR!     at WriteStream.emit (events.js:117:20)
npm ERR!     at evalmachine.<anonymous>:1609:14
npm ERR!     at c:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd c:\Users\Tony\Documents\dev\node_modules\grunt-refactor
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

**Comment by jonschlinkert** [comment]
> I got the following error message during the npm install for grunt-refactor. Please help

if this is something you're still interested in can you create an issue on the grunt-refactor repo? thanks
