### ISSUE TITLE
Version option doesn't allow absolute paths

### ISSUE THREAD

**Issue by jeffling** [assemble/assemble-less#14]
```
options: {
                version: '/usr/bin/less'
            }
```

gives the following error message

```
                                                              ^
Warning: Cannot find module '[...]webapp/usr/bin/less' Use --force to continue.
```

**Comment by jonschlinkert** [comment]
I can't see this being practical to use, what is the use case for this?

**Comment by jeffling** [comment]
I guess we're always supposed to use local less? I guess it's not an issue if there are advantages to it. Do you mind explaining why it's recommended though?

**Comment by jonschlinkert** [comment]
there are a few advantages of using local dependencies, but IMO the biggest advantage is that you can enforce whatever version you want for each project without concern for whatever version each team member has globally installed. when issues occur, it's always a pain to ask everyone what version of something they have globally installed. 

however, if this is something you need there are other ways we can require globally installed modules, versus using an absolute path. let me know if you still want this

**Comment by jeffling** [comment]
It's not really needed, the behaviour just seemed a bit counterintuitive, I didn't know this was done on purpose, or required extensive workaround to get working. 

-- 
Jeff

On 4 September, 2013 at 3:19:47 PM, Jon Schlinkert (notifications@github.com) wrote:

there are a few advantages of using local dependencies, but IMO the biggest advantage is that you can enforce whatever version you want for each project without concern for whatever version each team member has globally installed. when issues occur, it's always a pain to ask everyone what version of something they have globally installed.

however, if this is something you need there are other ways we can require globally installed modules, versus using an absolute path. let me know if you still want this

**Comment by jonschlinkert** [comment]
Fair enough, I guess what is "intuitive" is driven by how you prefer to work. If you use npm or bower to install less, then it's pretty simple to specify the version (or the path). 

Based on your reply, I'm closing the issue. but feel free to reopen if you want this implemented or want to discuss further.
