### ISSUE TITLE
@media query and mixin issue

### ISSUE THREAD

**Issue by kenilam** [assemble/assemble-less#23]
I am using assemble-less for a project I am building, and I have some variable like this:
@grid-size: 180px;
@wide: 12;
@min-wide: @wide \* @grid-size;

When I do: body { width: @min-wide; }

It output nicely like: body { width: 1620px; }

But when I do:
@media and all (min-width: @min-wide) { }

It output:
@media all and (max-width: 12 \* 180px) { }

I am not sure if it is a less bug or it has been fix on 1.7, or I am just not doing it correctly. But any suggestion would be much appreciate.

Thank you

**Comment by jonschlinkert** [comment]
please create an issue on less.js for this, thanks

**Comment by wide-zz** [comment]
Hi Dear why i get copy the email???  

Date: Sun, 23 Feb 2014 23:49:38 -0800

**Comment by jonschlinkert** [comment]
because @kenilam  didn't use backticks around their code.
