### ISSUE TITLE
grunt-lib-contrib is deprecated

### ISSUE THREAD

**Issue by sindresorhus** [assemble/assemble-less#24]
I noticed you use [grunt-lib-contrib](https://github.com/gruntjs/grunt-lib-contrib).

It's deprecated and I would recommend you switch to the extracted modules instead:
`stripPath` => [strip-path](https://github.com/sindresorhus/strip-path)
`minMaxInfo` => [maxmin](https://github.com/sindresorhus/maxmin)
`getNamespaceDeclaration` => [ticket](https://github.com/gruntjs/grunt-lib-contrib/issues/9)

**Comment by jonschlinkert** [comment]
thanks for this too. I've updated most of our other plugins, I guess this one needs some TLC
