### ISSUE TITLE
Pass metadata to Lo-Dash templates

### ISSUE THREAD

**Issue by laraduarte** [assemble/assemble-less#33]
Hi, i am trying to use metadata, but this is not working. 

i have this file - utils/data/yml/palette.yml with this content 
# palette.yml

topBarBg:    "purple"

on my settings file i have - @topBarBg :                                  <%= palette.topBarBg %>;

When i run override task the @topBarBg remains with the value <%= palette.topBarBg %>; and not purple. What am i doing wrong? can you help please? 

```
    less: {
        override: {
            options: {
                metadata: 'utils/data/yml/*.{json,yml}'
            },
            styles: {
                files: {
                    "app/css/app.css": ["app/less/app.less"]
                }
            }
        }
    },
```

**Comment by doowb** [comment]
Looks like you need to set `process: true` for it to run the source files through lodash.

``` js
    less: {
        override: {
            options: {
                process: true,
                metadata: 'utils/data/yml/*.{json,yml}'
            },
            styles: {
                files: {
                    "app/css/app.css": ["app/less/app.less"]
                }
            }
        }
    },
```

**Comment by laraduarte** [comment]
Well, its not working... what is supposed to do? 
replace background-color: <%= palette.topBarBg %>; by background-color: #123 in less file?
or when generate the css file do background-color: #123.

**Comment by laraduarte** [comment]
So, it is working now, as far as i can say, you need to define the vars in all pages. If you want this var @palette-info in 3 different files, in order this to work, you need to define them on all 3 less files. 
Can you explain why? i need a settings file with all the vars, and then use them whenever i need. Can you help please? thanks



//
// Palette
// --------------------------------------------------
@palette-info: <%= palette.info %>;
@palette-warning: <%= palette.warning %>;
@palette-danger: <%= palette.danger %>;
@palette-success: <%= palette.success %>;

.test {
    color: @palette-info;
    color: @palette-warning;
    color: @palette-danger;
    color: @palette-success;
}
