### ISSUE TITLE
Source map mediaquery is not correct

### ISSUE THREAD

**Issue by ruffle1986** [assemble/assemble-less#6]
Hi!

Have you checked sass/less supporting mediaquery in compiled css files?

When I set dumpLineNumbers option to 'mediaquery' (without compressing of course), the mediaquery info doesn't show the correct line number of the less definition in the compiled css file but shows the line number that points to the compiled css which is useless while developing with less.

If I compile with lessc command from terminal, everything works fine!

Could you solve this problem because source map would be very useful.

Here's a repo you can check this issue:
https://github.com/ruffle1986/less-workflow

just run 'npm install' and 'less:dev' task with grunt.

**Comment by jonschlinkert** [comment]
I'll take a look, thanks for pointing it out. If you want to do a pull request that would be good too

**Comment by ruffle1986** [comment]
Not at all. Maybe, I'll do a pull request but I can't guarantee.
