### ISSUE TITLE
"process" option doesn't do anything

### ISSUE THREAD

**Issue by dirkjanm** [assemble/assemble-less#7]
Currently the process option does not do anything.
The only lines I found which had something to do with processing are set after a return statement thus they never get executed.

**Comment by jonschlinkert** [comment]
Thanks for pointing that out. I will remove from docs, that feature has been removed.

**Comment by dirkjanm** [comment]
Why that? I kinda liked it. Any alternatives?

**Comment by jonschlinkert** [comment]
Me too actually, it's being "re-introduced" as soon as @doowb refactors part of the engine so that it's easier to add template engines.

**Comment by dirkjanm** [comment]
All right, I "fixed" it here by moving/changing

``` javascript
if (options.process) {
     lessCode = grunt.template.process(lessCode, options.process);
}
```

To the concatRender function (before the compiling).

**Comment by jonschlinkert** [comment]
You know what, I had a brain lapse. When I answered this I wasn't thinking - I pushed up like 4 repos in the last couple of days so I got mixed up.. 

I pushed up the process option yesterday (I think) but I had to make some changes. I'll be pushing some updates later today.  thanks
