### ISSUE TITLE
Documentation names task as assemble-less while the plugin uses "less"

### ISSUE THREAD

**Issue by dirkjanm** [assemble/assemble-less#8]
Some inconsistencies here:

Section header says

```
The "less" task
```

The section itself says

```
In your project's Gruntfile, add a section named assemble
```

The example code says "assemble-less" (which isn't even valid json and will give you a parse error).

The real plugin however uses the task "less". Took me some time to figure out as a guy new to this.

**Comment by jonschlinkert** [comment]
Wow, I'm sorry about this. You're finding errors that I mad in the readme's that have probably been there a while. The plugin is called "assemble-less", but the task section in the gruntfile is just "less". 

You should be able to download it, run `npm install` and then `grunt less` and it should just work. I'm actually pushing up some updates to this task today, so I'll get the docs fixed to. I'm happy to help or answer any questions
