### ISSUE TITLE
Default "version" option gives an error.

### ISSUE THREAD

**Issue by dirkjanm** [assemble/assemble-less#9]
When including assemble-less in my Gruntfile, I needed to manualy set version to

```
node_modules/assemble-less/test/versions/1.3.3
```

otherwise it gave me an error that it couldn't find less. I think the default assumes you are running the plugin from the main directory.

**Comment by doowb** [comment]
If you don't provide an option over `version`, we're defaulting it. I think in our testing, it was left as `../test/versions/1.3.3` and should be `less` so we just pull in the npm version of less that's installed. Thanks for pointing this out. We'll get it fixed shortly.

**Comment by jonschlinkert** [comment]
No, I defaulted it to a local dir for testing. Sorry it broke your setup, I was trying to resolve an issue with how it uses versions, and I wanted everything local for debugging. In any case, I have a lot of changes to push up for this repo, so hold tight. I'll try to push them up today if I can, but it might be tomorrow at the latest. 

Also, I might "re-release" the less-tests repo as "assemble-less-tests", and I'll move all of the different versions of less to that repo, with examples for how to wire them up. That way this one can stay bare bones. Thoughts?
